#host- Host on which awstats is configured
#domain- Domain to which awstats hat to setup

- hosts: "{{host}}" 
  remote_user: jayanth
  sudo: yes

  - name: copying files
    command: cp /etc/awstats/awstats.model.conf /etc/awstats/awstats."{{domain}}".conf
  - name: replacing LogFile  
    command: sed -i 's/access_log/{{domain}}-access_log/' /etc/awstats/awstats."{{domain}}".conf
  - name: Replacing SiteDomain
    command: sed -i 's/localhost.localdomain/{{domain}}/' /etc/awstats/awstats."{{domain}}".conf
  - name: Replacing HostAliases
    command: sed -i 's/^HostAliases.*/HostAliases="loalhost\ 127.0.0.1\ {{domain}}"/' /etc/awstats/awstats."{{domain}}".conf
  
