- hosts: all
  user: root
  sudo: no

  tasks:
   - name: installing httpd
     yum: name=httpd state=installed
#   - name: installing lynx
#     yum: name=lynx state=installed
#- include: reverseproxy.yaml 
 
