- hosts: reverse
  remote_user: root
  tasks:
   - name: copying conf file of virtual hosts
     synchronize: src=virtual-labs.ac.in.conf dest=/etc/httpd/conf.d/
   - name: restarting httpd
     service: name=httpd state=restarted
    
