- hosts: all
  remote_user: root

  # here we make a variable named "proxy_env" that is a dictionary
  vars:
    proxy_env:
      http_proxy: http://proxy.iiit.ac.in:8080/
      https_proxy: http://proxy.iiit.ac.in:8080/

  tasks:

    - yum: name=* update_cache=yes
      environment: proxy_env
- include: httpd.yaml

